// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsuNVDxMLAr5rjIW7ODVWj5uZqQg7glao',
    appId: '1:611965525994:web:7fd86aa952905e61f89c93',
    messagingSenderId: '611965525994',
    projectId: 'daily-english-vocabulary',
    authDomain: 'daily-english-vocabulary.firebaseapp.com',
    storageBucket: 'daily-english-vocabulary.firebasestorage.app',
    measurementId: 'G-34GDNGG6VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL9XMr8AcGMlDdUuG7uzZRnn-lJkbSED8',
    appId: '1:611965525994:android:c4f47de8da900d5ff89c93',
    messagingSenderId: '611965525994',
    projectId: 'daily-english-vocabulary',
    storageBucket: 'daily-english-vocabulary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV3ibJfwk47br-pzgXTUcOh7TrB4ZG9b0',
    appId: '1:611965525994:ios:e8ea16859c0b7558f89c93',
    messagingSenderId: '611965525994',
    projectId: 'daily-english-vocabulary',
    storageBucket: 'daily-english-vocabulary.firebasestorage.app',
    iosBundleId: 'com.example.dailyEnglishVocabulary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV3ibJfwk47br-pzgXTUcOh7TrB4ZG9b0',
    appId: '1:611965525994:ios:e8ea16859c0b7558f89c93',
    messagingSenderId: '611965525994',
    projectId: 'daily-english-vocabulary',
    storageBucket: 'daily-english-vocabulary.firebasestorage.app',
    iosBundleId: 'com.example.dailyEnglishVocabulary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsuNVDxMLAr5rjIW7ODVWj5uZqQg7glao',
    appId: '1:611965525994:web:c18d2555e4dbbcb1f89c93',
    messagingSenderId: '611965525994',
    projectId: 'daily-english-vocabulary',
    authDomain: 'daily-english-vocabulary.firebaseapp.com',
    storageBucket: 'daily-english-vocabulary.firebasestorage.app',
    measurementId: 'G-Y0GHP6MSBV',
  );
}
